# Generated by Django 4.0.1 on 2022-01-07 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='parent',
        ),
    ]
