# Generated by Django 4.0.1 on 2022-01-11 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_remove_tweet_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='image',
        ),
    ]
